# Copyright 2021 Diko Parvanov
# See LICENSE file for licensing details.

options:
  probe-interval:
    default: 300
    description: |
      Duration of the base operation interval of SmokePing in seconds.
      SmokePing will venture out every step seconds to ping your target hosts.
      IMPORTANT: Changing this config option will remove historical data as per 
      Smokeping functionality.
    type: int
  targets:
    default: "[]"
    description: |
      JSON formatted file of targets with names and hosts to monitor.
      For example: [ { "unit_name": "GoogleDNS", "host": "8.8.8.8" } ]
    type: string
  timezone:
    default: "Europe/London"
    description: |
      Timezone to use.
    type: string
